### ISSUE TITLE
Fetch videos in 1000 Apps Dataset

### ISSUE THREAD

**Issue by alivcor** [iresium/apprater#2]
We need to fetch videos/screenshot data for all apps in 1000 apps.

**Comment by alivcor** [comment]
@praneethgb start working on this.

**Comment by alivcor** [comment]
We need to complete this before November 2. @praneethgb

**Comment by praneethgb** [comment]
Okay, @alivcor . what are you up to?

**Comment by alivcor** [comment]
I'm working on #1 as well.

**Comment by praneethgb** [comment]
Today, I will grep videos from 1000 apps dataset.
